[package]
name = "autodiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
once_cell = "1.8.0"

[dev-dependencies]
rand = "0.8"
proptest = "1.0"
approx = "0.5"